[project]
name = "sdrc_cloudlog"
version = "0.0.1"
requires-python = ">= 3.12"
authors = [
    { name = "Matt G4IYT", email = "matt@g4iyt.uk" }
]
readme = "README.md"
dependencies = {file = ["requirements.txt"]}

[project.scripts]
sdrc-cloudlog = "sdrc_cloudlog.__main__:main"