name: Release (Windows)
on:
  push:
    tags:
      - 'v*'
jobs:
  release-windows:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: pip install
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Package with PyInstaller
        run: |
          $site = (python -c "import sysconfig; print(sysconfig.get_path('purelib'))")
          pyinstaller --noconfirm --onedir --windowed --add-data "$site/customtkinter:customtkinter" entry.py

          cd dist\entry
          ren entry.exe sdrc-cloudlog.exe
          compress-archive -path .\* -destinationpath ..\..\dist.zip
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist.zip
          asset_name: sdrc-cloudlog.zip
          asset_content_type: application/octet-stream
